#!/bin/bash
#mv test-1/dir--{00..10}/file-{00..10} test-1/dir--{00..10}/file-{00..10}s

for f in test-1/dir*/file*
do
	IFS=/ read -r a b c <<< "$f"
	if [[ $f == *"$1"* ]]; then
		echo $c
		s="${c/$1/$2}"
		mv -- "$f" "${$f/$c/$s}"
	fi;
done
